### ISSUE TITLE
Add 4.2 screenshots 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation-docs#214]
I don't think we have to replace _all_ the screenshots right away, but we should take a pass through the docs and make sure that we at prioritize replace the screenshots that involves the Qubes menu, Devices widget, and other bigger changes.

**Comment by eloquence** [comment]
Surveying the screenshots in the docs, I'm prioritizing approximately as follows:
- High: Installation screenshots documenting how to copy the submission key from an SVS drive (https://workstation.securedrop.org/en/stable/admin/install.html)
- Medium: System tray screenshots in network troubleshooting guide (https://workstation.securedrop.org/en/stable/admin/troubleshooting_connection.html); maybe others on that page if there are noticeable changes
- Low: Everything else

I didn't spot any screenshots of the main menu, though a bunch of the textual descriptions will need to be updated.

**Comment by eloquence** [comment]
Collecting first round of screenshots here before I prepare the PR. One caveat for the docs -- when mounting a Tails drive in Thunar, it shows a "permission denied" error for me, presumably because the files are mounted with root-exclusive permissions and I am non-root. I recall seeing this before but I don't know if there's a simple workaround that doesn't involve mucking about with udev rules. Either way though, the files are accessible for the root user.

Device manager with `vault` VM selected:
![desktop-device-selected](https://github.com/freedomofpress/securedrop-workstation-docs/assets/213636/2903680c-a6cb-418e-a490-65b47dc78543)

Encrypted volume available in Thunar:
![device-in-thunar](https://github.com/freedomofpress/securedrop-workstation-docs/assets/213636/38742d34-a0fc-47ec-bdd6-935fc2644ad5)

Plain Qubes 4.2 desktop with SDW installed:
![desktop-plain](https://github.com/freedomofpress/securedrop-workstation-docs/assets/213636/43456ce7-ed50-4faa-8b01-9dd80c7f646d)

Updater launched:
![desktop-updater](https://github.com/freedomofpress/securedrop-workstation-docs/assets/213636/eccf279a-d900-43b7-b575-cc0d28db0510)

Updates in progress:
![desktop-updates-in-progress](https://github.com/freedomofpress/securedrop-workstation-docs/assets/213636/f759e175-01ee-42f8-8467-eac55529c1ab)

**Comment by eloquence** [comment]
Draft PR ready in #219, based off #217 and draft until that's merged.

**Comment by rocodes** [comment]
closing per https://github.com/freedomofpress/securedrop-workstation-docs/issues/214#issuecomment-2187078224
